version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: expense_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: expenses
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - expense_network

  app:
    build: .
    container_name: expense_tracker_app
    restart: always
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_DB: expenses
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - expense_network

networks:
  expense_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
